development:
  sessions:
    default:
      database: illuminati
      hosts:
        - illuminati_mongo:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: illuminati-test
      hosts:
        - illuminati_mongo:27017
  options:
    raise_not_found_error: false

travis:
  sessions:
    default:
      database: illuminati-test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
